apiVersion : apps/v1
kind: Deployment
metadata:
  name: deyvicarlosapipruebaaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deyvicarlosapipruebaaks
  template:
    metadata:
      labels:
        app: deyvicarlosapipruebaaks 
    spec:
      containers:
        - name: deyvicarlosapipruebaaks 
          image: registrocotenedorprueba7.azurecr.io/deyvicarlosapipruebaaks
          ports:
          - containerPort: 4000