apiVersion : apps/v1
kind: Deployment
metadata:
  name: sananatural-deployment
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sananatural-deployment
  template:
    metadata:
      labels:
        app: sananatural-deployment
    spec:
      containers:
        - name: sananatural-server
          image: contenedorregistrosananatural.azurecr.io/sananatural
          ports:
            - containerPort: 4000
